# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0687aeda1fe37dcea4968ee84e9284f3adef443843ef64b17c8d323845a849c67282a1de65cda8d548c00716be8faf820b4a70c3d7ec61a4dff723c5863835dd

test:
  secret_key_base: f6018380ad78db381c3348667740eb39c93ebae966abd526dab4f2b34e24125d112bcda6c564647a936512640acca3193231a4b7c0a36ca837a2426700a6e450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
